/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ProbePanel.java
 *
 * Created on Dec 15, 2011, 12:36:44 PM
 */
package edu.ucdenver.ccp.phenogen.applets.exonviewer;

import edu.ucdenver.ccp.phenogen.applets.data.Probe;
import edu.ucdenver.ccp.phenogen.applets.data.ProbeSet;
import java.util.ArrayList;

/**
 *
 * @author smahaffey
 */
public class ProbeSetPanel extends javax.swing.JPanel {
//TODO Make the go to Affy button work
    /** Creates new form ProbePanel */
    public ProbeSetPanel() {
        initComponents();
    }
    
    public void setProbe(ProbeSet probe){
        if(probe!=null){
            IDlbl.setText("ProbeSet ID:  "+probe.getProbeSetID());
            Sequencetxt.setText(probe.getSequence());
            Startlbl.setText("Location bp: ("+probe.getStart()+":"+probe.getStop()+")");
            Annotationlbl.setText("Annotation:  "+probe.getAnnotation());
            Strandlbl.setText("Strand:  "+probe.getStrand());
            probeList.removeAll();
            ArrayList<Probe> probes=probe.getProbes();
            probeList.setListData(probes.toArray());
            if(probes.size()>0){
                probeList.setSelectedIndex(0);
            }
            if(probe.getDabg()>-1){
                dabglbl.setText("% Samples DABG:  "+probe.getDabg()+"%");
            }else{
                dabglbl.setText("% Samples DABG:  N/A");
            }
            if(probe.getHerit()>-1){
                heritlbl.setText("Heritability:  "+probe.getHerit());
            }else{
                heritlbl.setText("Heritability:  N/A");
            }
            /*if(probe.isMasked()){
                maskedlbl.setText("Masked:  Yes");
            }else{
                maskedlbl.setText("Masked:  No");
            }*/
            if(probe.isExcluded()){
                filterlbl.setVisible(true);
                filterlbl.setText("Filtered by:  "+probe.getExclusionReason());
            }else{
                filterlbl.setVisible(false);
            }
            if(probe.getProbes()!=null&&probe.getProbes().size()>0){
                probePanel1.setProbe(probe.getProbes().get(0));
            }
        }else{
            IDlbl.setText("ProbeSet ID:");
            Sequencetxt.setText("");
            Startlbl.setText("Start:");
            
            Annotationlbl.setText("Annotation:");
            Strandlbl.setText("Strand:");
            dabglbl.setText("% Samples DABg:");
            heritlbl.setText("Heritability:");
            //maskedlbl.setText("Masked:");
            filterlbl.setText("Filtered by:");
            ArrayList<Probe> probes=new ArrayList<Probe>();
            probeList.setListData(probes.toArray());
            probePanel1.setProbe(null);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        IDlbl = new javax.swing.JLabel();
        Startlbl = new javax.swing.JLabel();
        Annotationlbl = new javax.swing.JLabel();
        Strandlbl = new javax.swing.JLabel();
        dabglbl = new javax.swing.JLabel();
        heritlbl = new javax.swing.JLabel();
        filterlbl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Sequencetxt = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        probeList = new javax.swing.JList();
        probePanel1 = new edu.ucdenver.ccp.phenogen.applets.exonviewer.ProbePanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(200, 100));
        setLayout(new java.awt.GridLayout(2, 1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        IDlbl.setText("Probe Set ID:");

        Startlbl.setText("Location bp:");

        Annotationlbl.setText("Annotation:");

        Strandlbl.setText("Strand:");

        dabglbl.setText("% Samples DABg:");

        heritlbl.setText("Heritability:");

        filterlbl.setText("Filtered by:");

        org.jdesktop.layout.GroupLayout jPanel5Layout = new org.jdesktop.layout.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(IDlbl)
                    .add(Annotationlbl)
                    .add(dabglbl))
                .add(23, 23, 23)
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(Startlbl)
                    .add(jPanel5Layout.createSequentialGroup()
                        .add(Strandlbl)
                        .add(18, 18, 18)
                        .add(filterlbl))
                    .add(heritlbl))
                .add(0, 264, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(IDlbl)
                    .add(Startlbl))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(Annotationlbl)
                    .add(Strandlbl)
                    .add(filterlbl))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(dabglbl)
                    .add(heritlbl))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel5, java.awt.BorderLayout.NORTH);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel6.setText("ProbeSet Sequence:");
        jPanel2.add(jLabel6, java.awt.BorderLayout.NORTH);

        Sequencetxt.setColumns(20);
        Sequencetxt.setLineWrap(true);
        Sequencetxt.setRows(5);
        jScrollPane1.setViewportView(Sequencetxt);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Probe List:");
        jPanel3.add(jLabel1, java.awt.BorderLayout.NORTH);

        probeList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        probeList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                probeListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(probeList);

        jPanel3.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3);

        jPanel4.add(jPanel1, java.awt.BorderLayout.CENTER);

        add(jPanel4);
        add(probePanel1);
    }// </editor-fold>//GEN-END:initComponents

    private void probeListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_probeListValueChanged
        probePanel1.setProbe((Probe)probeList.getSelectedValue());
    }//GEN-LAST:event_probeListValueChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Annotationlbl;
    private javax.swing.JLabel IDlbl;
    private javax.swing.JTextArea Sequencetxt;
    private javax.swing.JLabel Startlbl;
    private javax.swing.JLabel Strandlbl;
    private javax.swing.JLabel dabglbl;
    private javax.swing.JLabel filterlbl;
    private javax.swing.JLabel heritlbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList probeList;
    private edu.ucdenver.ccp.phenogen.applets.exonviewer.ProbePanel probePanel1;
    // End of variables declaration//GEN-END:variables
}
